repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.1
    hooks:
      - id: typos
        files: ^frontend/src/
        exclude: ^frontend/storybook-static/|^frontend/dist/|^frontend/node_modules/
